<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="object_iiwa">

    <xacro:arg name="hardware_interface" default="EffortJointInterface"/>
    <xacro:arg name="initial_z" default="0.0"/>
    <xacro:arg name="mass" default="3.4"/>   
    
    <link name="world"/>

    <xacro:include filename="$(find iiwa_description)/urdf/object_iiwa14.xacro"/>
    <xacro:include filename="$(find iiwa_description)/urdf/materials.xacro"/>
	
    <xacro:arg name="robot_name" default="object_iiwa"/>
    <xacro:arg name="hardware_interface" default="PositionJointInterface"/>

    <joint name="$(arg robot_name)_world_joint" type="fixed">
        <parent link="world"/>
        <child link="$(arg robot_name)_link_0"/>
        <origin xyz="0.0 0.0 ${$(arg initial_z) + 0.008}" rpy="0.0 0.0 ${0.0}"/>
    </joint>
    
    <xacro:iiwa14 hardware_interface="$(arg hardware_interface)" robot_name="$(arg robot_name)">
    </xacro:iiwa14>
<!---->
    <xacro:include filename="$(find iiwa_description)/urdf/weighted_object.xacro"/>
    <xacro:weighted_object mass="$(arg mass)"/>
    
    <joint name="$(arg robot_name)_ee_to_object" type="fixed">
        <parent link="$(arg robot_name)_link_ee"/>
        <child link="object_link_0"/>
		<origin xyz="0.0 0.0 0.1" rpy="${0.0} ${0.0} ${0.0}"/>
    </joint>

</robot>
