  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  

  PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - object_iiwa_joint_1
      - object_iiwa_joint_2
      - object_iiwa_joint_3
      - object_iiwa_joint_4
      - object_iiwa_joint_5
      - object_iiwa_joint_6
      - object_iiwa_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  500            # Override default
    action_monitor_rate: 500            # Override default
    stop_trajectory_duration: 0        # Override default
    
  EffortJointInterface_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - object_iiwa_joint_1
      - object_iiwa_joint_2
      - object_iiwa_joint_3
      - object_iiwa_joint_4
      - object_iiwa_joint_5
      - object_iiwa_joint_6
      - object_iiwa_joint_7
    gains:
      object_iiwa_joint_1: {p: 120,  d: 10, i: 4, i_clamp: 1000}
      object_iiwa_joint_2: {p: 164,  d: 75, i: 35, i_clamp: 1000}
      object_iiwa_joint_3: {p: 75,  d: 0.6, i: 3.15, i_clamp: 1000}
      object_iiwa_joint_4: {p: 138,  d: 60, i: 25, i_clamp: 1000}
      object_iiwa_joint_5: {p: 70,  d: 0.15, i: 1, i_clamp: 1000}
      object_iiwa_joint_6: {p: 85,  d: 7, i: 2.5, i_clamp: 1000}
      object_iiwa_joint_7: {p: 10,  d: 0.005, i: 0.1, i_clamp: 1000}
      
    constraints:
      goal_time: 1                  # Override default

    state_publish_rate:  500            # Override default
    action_monitor_rate: 500            # Override default
    stop_trajectory_duration: 0        # Override default
